<main class="yellowWave">
    <div class="container accountContainer">
        <div class="accountAccess">
            <p>Bonjour <?=  $_SESSION["user"]["name"] ?> <?=  $_SESSION["user"]["lastname"] ?> !</p>
            <p><a href="index.php?action=account">Tableau de bord</a></p>
            <p><a href="index.php?action=account&myOrders">Mes commandes</a></p>
            <p class="actual"><a href="index.php?action=account&myInfos">Mes informations</a></p>
            <ul>
                    <li class="actual"><a href="index.php?action=modifyAccount">Modifier mes informations</a></li>
                    <?php if($userController -> newsletter_joined()) : ?>
                        <li><a href="index.php?action=changeNewsletter&suppNewsletter">Me désinscrire de la newsletter</a></li>
                    <?php else : ?>
                        <li><a href="index.php?action=changeNewsletter">M'inscrire à la newsletter</a></li>
                    <?php endif; ?>
                    <li><a href="index.php?action=modifyPassword">Modifier mon mot de passe</a></li>
                    <li><a href="index.php?action=deleteUser">Supprimer mon compte</a></li>
                </ul>
            <p><a href="index.php?action=disconnect">Se déconnecter</a></p>
        </div>

        <div class="accountContent modifyInfos">
            <h1>Modifier mes informations</h1>
            <form action="index.php?action=modifyAccount" method="post">
                <?php if(isset($message)) : ?>
                    <div class="message"><?= $message ?></div>
                <?php endif; ?>

                <p><label>Nom :</label></p>
                <p><input type="text" name="lastname" value="<?= $user["lastname"] ?>"></p>
                <p><label>Prénom :</label></p>
                <p><input type="text" name="name" value="<?= $user["name"] ?>"></p>
                <p><label>Date de naissance :</label></p>
                <p><input type="date" name="date" value="<?= $user["birthdate"] ?>"></p>
                <p><label>Adresse :</label></p>
                <p><input type="text" name="adress" value="<?= $user["adress"] ?>"></p>
                <p><label>Ville</label></p>
                <p><input type="text" name="city" value="<?= $user["city"] ?>"></p>
                <p><label>Code postal :</label></p>
                <p><input type="text" name="postcode" value="<?= $user["postcode"] ?>"></p>
                <p><label>Pays :</label></p>
                <p><input type="text" name="country" value="<?= $user["country"] ?>"></p>
                <p><label>Téléphone :</label></p>
                <p><input type="tel" name="phone" value="<?= $user["phone"] ?>"></p>
                <p><label>Email :</label></p>
                <p><input type="email" name="email" value="<?= $user["email"] ?>"></p>
                
                <div class="accountButtons">
                    <button type="submit" value="submit">Modifier</button>
                    <button type="reset" value="reset">Annuler</button>
                </div>
            </form>
        </div>
    </div>
</main>