<main class="yellowWave">
    <div class="container accountContainer">   
    <div class="accountAccess">
        <p>Bonjour <?=  $_SESSION["user"]["name"] ?> <?=  $_SESSION["user"]["lastname"] ?> !</p>
        <p><a href="index.php?action=account">Tableau de bord</a></p>
        <p><a href="index.php?action=account&myOrders">Mes commandes</a></p>
        <p class="actual"><a href="index.php?action=account&myInfos">Mes informations</a></p>
        <ul>
                <li><a href="index.php?action=modifyAccount">Modifier mes informations</a></li>
                <?php if($userController -> newsletter_joined()) : ?>
                    <li><a href="index.php?action=changeNewsletter&suppNewsletter">Me désinscrire de la newsletter</a></li>
                <?php else : ?>
                    <li><a href="index.php?action=changeNewsletter">M'inscrire à la newsletter</a></li>
                <?php endif; ?>
                <li class="actual"><a href="index.php?action=modifyPassword">Modifier mon mot de passe</a></li>
                <li><a href="index.php?action=deleteUser">Supprimer mon compte</a></li>
            </ul>
            <p><a href="index.php?action=disconnect">Se déconnecter</a></p>
        </div>

        <div class="accountContent modifyInfos">
            <h1>Mot de passe</h1>
            <form action="index.php?action=modifyPassword" method="post">
                <?php if(isset($message)) : ?>
                    <div class="message"><?= $message ?></div>
                <?php endif; ?>

                <label>Ancien mot de passe : </label>
                <input type="password" name="oldPassword">
                <label>Nouveau mot de passe : </label>
                <input type="password" name="newPassword">
                <div class="accountButtons">
                    <button type="submit" value="submit">Modifier</button>
                    <button type="reset" value="reset">Annuler</button>
                </div>
            </form>
        </div>
    </div>
</main>