<main class="yellowWave">
    <div class="container">
        <h1>Modification du compte admin</h1>
        <form action="index.php?action=modifyAdmin" method="post" enctype="multipart/form-data" class="adminForms">
            <?php if(isset($message)) : ?>
                <div class="message"><?= $message ?></div>
            <?php endif; ?>
            <p><label>Adresse email actuelle :</label></p>
            <input type="email" name="oldEmail">
            <p><label>Nouvelle adresse email :</label></p>
            <input type="email" name="newEmail">
            <p><label>Mot de passe actuel :</label></p>
            <input type="password" name="oldPassword">
            <p><label>Nouveau mot de passe :</label></p>
            <input type="password" name="newPassword">
            <div class="adminSubmitButtons">
                <button type="submit" value="submit">Modifier</button>
                <button type="reset" value="reset">Annuler</button>
            </div>
        </form>
    </div>
</main>