<main class="yellowWave">
    <div class="container">
        <?php if(array_key_exists("id",$_GET)) : ?>
            <h1>Modifier le slider</h1>
            <?php if($eventController -> on_slider()) : ?>
                <div class="centerAdminButton">
                    <a href="index.php?action=adminSlider&id=<?= $info["id_event"] ?>&suppSlider" class="adminButton">Supprimer la bannière</a>
                </div>
                <img src="www/images/banners/<?= $info["banner"] ?>" alt="<?= $info["banner"] ?>">
                <form action="index.php?action=adminSlider&id=<?= $info["id_event"] ?>&changeSlider" method="post" enctype="multipart/form-data" class="adminForms">
                    <?php if(isset($message)) : ?>
                        <div class="message"><?= $message ?></div>
                    <?php endif; ?>
                    <p><label>Nouvelle bannière :</label></p>
                    <input type="file" name="banner">
                    <div class="adminSubmitButtons">
                        <button type="submit" value="submit">Modifier</button>
                        <button type="reset" value="reset">Annuler</button>
                    </div>
                </form>
            <?php else : ?>
                <form action="index.php?action=adminSlider&id=<?= $info["id_event"] ?>&changeSlider" method="post" enctype="multipart/form-data" class="adminForms">
                    <?php if(isset($message)) : ?>
                        <div class="message"><?= $message ?></div>
                    <?php endif; ?>
                    <p><label>Nouvelle bannière :</label></p>
                    <input type="file" name="banner">
                    <div class="adminSubmitButtons">
                        <button type="submit" value="submit">Modifier</button>
                        <button type="reset" value="reset">Annuler</button>
                    </div>
                </form>
            <?php endif; ?>

        <?php else : ?>

            <h1>Gestion du slider</h1>

            <?php if(array_key_exists("message",$_GET)) : ?>
                <div class="message"><?= $_GET["message"] ?></div>
            <?php endif; ?>
            <table>
                <thead>
                    <tr>
                        <td>Artiste</td>
                        <td>Tournée</td>
                        <td>Date</td>
                        <td>Sur slider ?</td>
                        <td>Ajouter/supprimer du slider ?</td>
                    </tr>
                </thead>
            <?php foreach($events as $event) : ?>
                <tr>
                    <td data-label="Artiste"><?= $event["artist"] ?></td>
                    <td data-label="Tournée"> <?= $event["name"] ?></td>
                    <td data-label="Date"><?= $event["date"] ?></td>
                    <td data-label="Slider ?"><?= $event["on_slider"] ?></td>
                    <td data-label="Ajouter/supprimer ?"><a href="index.php?action=adminSlider&id=<?= $event["id_event"] ?>">Modifier</a></td>
                </tr>
            <?php endforeach; ?>
            </table>

        <?php endif; ?>
    </div>
</main>