<?php $userController = new UserController(); ?>

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title><?= $titre ?></title>
    <meta name="viewport" content="width=device-width">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Bebas+Neue&family=Oxygen:wght@300&family=Roboto:ital,wght@0,400;0,500;1,400&display=swap" rel="stylesheet">
    <script src="https://code.jquery.com/jquery-3.4.1.min.js"
			  integrity="sha256-CSXorXvZcTkaix6Yvo6HppcZGetbYMGWSFlBw8HfCJo="
			  crossorigin="anonymous"></script>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v6.0.0/css/all.css">
    <link rel="stylesheet" href="www/css/normalize.css" type="text/css">
    <link rel="stylesheet" href="www/css/style.css" type="text/css">
</head>
<body class="user">
    <header>
        <i class="fas fa-bars" id="menuMobile"></i>
        <i class="fas fa-times hidden closeSearch" id="closeSearch"></i>
        <div class="logoTitle">
            <img src="www/images/logo.png" alt="logo" class="logo">
            <div class="title"><a href="index.php">Radioactive</a></div>
        </div>

        <nav id="navMenu" class="hiddenNav">
            <ul>
                <li><a href="index.php">Accueil</a></li>
                <li><a href="index.php?action=tickets">Billetterie</a></li>
                <li><a href="index.php?action=practical">Infos pratiques</a></li>
                <li><a href="index.php?action=contact">Contact</a></li>
                <li>
                    <a href="index.php?action=basket" class="basket">
                        <i class="fa fa-shopping-bag"></i>
                        <span class="basketNumber" id="numberBasket"></span>
                    </a>
                </li>
                <li>
                    <i class="fas fa-search" id="searchGlass"></i>
                </li>
                <?php if($userController -> is_connected()) : ?>
                    <li class="access">
                        <a href="index.php?action=account"><i class="fas fa-user"></i></a>
                    </li>
                    <li class="access">
                        <a href="index.php?action=disconnect"><i class="fas fa-sign-out-alt"></i></a>
                    </li>
                <?php else : ?>
                    <li class="access">
                        <a href="index.php?action=login"><i class="fas fa-user"></i></a>
                    </li>
                <?php endif; ?>
            </ul>
        </nav>
        <div class="accessMobile">
            <?php if($userController -> is_connected()) : ?>
                    <a href="index.php?action=account"><i class="fas fa-user"></i></a>
                    <a href="index.php?action=disconnect"><i class="fas fa-sign-out-alt"></i></a>
            <?php else : ?>
            <a href="index.php?action=login"><i class="fas fa-user"></i></a>
            <?php endif; ?>
        </div>
        <form class="hiddenSearch searching" id="searchForm">
            <div class="searchFormContent">
                <label class="searchLabel">Recherche :</label>
                <div class="searchBarContainer">
                    <input type="search" name="search" id="search" placeholder="Chercher un concert, un artiste" class="searchBar">
                </div>
                <div id="searchResults" class="searchResults">
                </div>
            </div>
        </form>
    </header>
    
    <?php require $template.".phtml"; ?>

    <footer>
        <div class="footerContainer">
            <div class="footerLogo">
                <div class="logoTitleFooter">
                    <img src="www/images/logo.png" alt="logo" class="logo">
                    <div class="title"><a href="index.php">Radioactive</a></div>
                </div>
            </div>

            <div class="footerLinks">
                <a href="index.php?action=tickets">Billetterie</a>
                <a href="index.php?action=practical">Infos pratiques</a>
                <a href="">Mentions légales</a>
                <a href="">Conditions générales de vente</a>
                <a href="index.php?action=contact">Contact</a>
            </div>

            <div class="footerSocial">
                <a href=""><i class="fab fa-facebook-f"></i></a>
                <a href=""><i class="fab fa-instagram"></i></a>
                <a href=""><i class="fab fa-twitter"></i></a>
                <a href=""><i class="fab fa-youtube"></i></a>
            </div>
        </div>
    </footer>

    <script type="text/javascript" src="www/js/addBasket.js"></script>
    <script type="text/javascript" src="www/js/searchBar.js"></script>
    <script type="text/javascript" src="www/js/revealTickets.js"></script>
</body>
</html>