<main class="yellowWave">
    <div class="container practical">
        <h1>Infos pratiques</h1>

        <div class="reveal">

            <img src="www/images/image-one.jpg" alt="image une">

            <div>
                <h2>Titre</h2>

                <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi augue eros, aliquet ut nisi at, rutrum feugiat ligula. Donec sit amet metus euismod, efficitur tortor sit amet, tempus nisi. Maecenas porta magna metus, sed sollicitudin arcu commodo a. Nulla at sollicitudin diam. Fusce varius pellentesque est ac ultrices. Maecenas ex enim, finibus et eros at, mattis hendrerit tortor. Integer vestibulum sagittis nibh sit amet laoreet. Maecenas vitae laoreet tellus. Proin sed dolor ac lorem fermentum lacinia. Aliquam facilisis erat sem, non fringilla neque sollicitudin ut. Cras quis tempor felis. Maecenas quis nisi pretium, malesuada risus quis, pulvinar nunc.</p>

                <p>Pellentesque ut neque vitae nibh malesuada commodo quis id nulla. Integer feugiat elementum lorem, quis mollis neque molestie ut. Cras in maximus metus. Cras vestibulum elit vel consequat rhoncus. Nullam vitae congue dui, vitae gravida magna. Nunc felis odio, fermentum vitae mi ac, sodales tempus orci. In auctor urna ac urna eleifend lobortis. Pellentesque sit amet ultrices turpis, id volutpat ligula. Nam et malesuada arcu. In hac habitasse platea dictumst. Sed mauris neque, porta sed tristique quis, dignissim at neque.</p>

                <p>Proin bibendum posuere quam quis efficitur. Morbi ligula mauris, bibendum vitae mi sit amet, ultrices placerat lectus. Ut dui lectus, ultricies sit amet est tempus, ultricies dignissim augue. In congue, augue ut sagittis sollicitudin, odio est volutpat sapien, ut vulputate arcu arcu vel sem. Praesent dapibus ipsum eu nisl porttitor posuere. Sed dolor odio, lacinia vitae dictum nec, imperdiet in dolor. Donec eros orci, fermentum id eleifend vitae, posuere condimentum arcu.</p>

                <div class="clearfix"></div>
            </div>
        </div>
        
        <div class="reveal">

            <img src="www/images/image-two.jpg" alt="image deux">

            <div>
                <h2>Titre</h2>

                <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi augue eros, aliquet ut nisi at, rutrum feugiat ligula. Donec sit amet metus euismod, efficitur tortor sit amet, tempus nisi. Maecenas porta magna metus, sed sollicitudin arcu commodo a. Nulla at sollicitudin diam. Fusce varius pellentesque est ac ultrices. Maecenas ex enim, finibus et eros at, mattis hendrerit tortor. Integer vestibulum sagittis nibh sit amet laoreet. Maecenas vitae laoreet tellus. Proin sed dolor ac lorem fermentum lacinia. Aliquam facilisis erat sem, non fringilla neque sollicitudin ut. Cras quis tempor felis. Maecenas quis nisi pretium, malesuada risus quis, pulvinar nunc.</p>

                <p>Pellentesque ut neque vitae nibh malesuada commodo quis id nulla. Integer feugiat elementum lorem, quis mollis neque molestie ut. Cras in maximus metus. Cras vestibulum elit vel consequat rhoncus. Nullam vitae congue dui, vitae gravida magna. Nunc felis odio, fermentum vitae mi ac, sodales tempus orci. In auctor urna ac urna eleifend lobortis. Pellentesque sit amet ultrices turpis, id volutpat ligula. Nam et malesuada arcu. In hac habitasse platea dictumst. Sed mauris neque, porta sed tristique quis, dignissim at neque.</p>

                <p>Proin bibendum posuere quam quis efficitur. Morbi ligula mauris, bibendum vitae mi sit amet, ultrices placerat lectus. Ut dui lectus, ultricies sit amet est tempus, ultricies dignissim augue. In congue, augue ut sagittis sollicitudin, odio est volutpat sapien, ut vulputate arcu arcu vel sem. Praesent dapibus ipsum eu nisl porttitor posuere. Sed dolor odio, lacinia vitae dictum nec, imperdiet in dolor. Donec eros orci, fermentum id eleifend vitae, posuere condimentum arcu.</p>
                
                <div class="clearfix"></div>
            </div>
        </div>

        <div class="reveal">

            <img src="www/images/image-three.jpg" alt="image trois">

            <div>
                <h2>Titre</h2>

                <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi augue eros, aliquet ut nisi at, rutrum feugiat ligula. Donec sit amet metus euismod, efficitur tortor sit amet, tempus nisi. Maecenas porta magna metus, sed sollicitudin arcu commodo a. Nulla at sollicitudin diam. Fusce varius pellentesque est ac ultrices. Maecenas ex enim, finibus et eros at, mattis hendrerit tortor. Integer vestibulum sagittis nibh sit amet laoreet. Maecenas vitae laoreet tellus. Proin sed dolor ac lorem fermentum lacinia. Aliquam facilisis erat sem, non fringilla neque sollicitudin ut. Cras quis tempor felis. Maecenas quis nisi pretium, malesuada risus quis, pulvinar nunc.</p>

                <p>Pellentesque ut neque vitae nibh malesuada commodo quis id nulla. Integer feugiat elementum lorem, quis mollis neque molestie ut. Cras in maximus metus. Cras vestibulum elit vel consequat rhoncus. Nullam vitae congue dui, vitae gravida magna. Nunc felis odio, fermentum vitae mi ac, sodales tempus orci. In auctor urna ac urna eleifend lobortis. Pellentesque sit amet ultrices turpis, id volutpat ligula. Nam et malesuada arcu. In hac habitasse platea dictumst. Sed mauris neque, porta sed tristique quis, dignissim at neque.</p>

                <p>Proin bibendum posuere quam quis efficitur. Morbi ligula mauris, bibendum vitae mi sit amet, ultrices placerat lectus. Ut dui lectus, ultricies sit amet est tempus, ultricies dignissim augue. In congue, augue ut sagittis sollicitudin, odio est volutpat sapien, ut vulputate arcu arcu vel sem. Praesent dapibus ipsum eu nisl porttitor posuere. Sed dolor odio, lacinia vitae dictum nec, imperdiet in dolor. Donec eros orci, fermentum id eleifend vitae, posuere condimentum arcu.</p>

                <div class="clearfix"></div>
            </div>
        </div>

        <div class="reveal">

            <img src="www/images/image-four.jpg" alt="image quatre">

            <div>
                <h2>Titre</h2>

                <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi augue eros, aliquet ut nisi at, rutrum feugiat ligula. Donec sit amet metus euismod, efficitur tortor sit amet, tempus nisi. Maecenas porta magna metus, sed sollicitudin arcu commodo a. Nulla at sollicitudin diam. Fusce varius pellentesque est ac ultrices. Maecenas ex enim, finibus et eros at, mattis hendrerit tortor. Integer vestibulum sagittis nibh sit amet laoreet. Maecenas vitae laoreet tellus. Proin sed dolor ac lorem fermentum lacinia. Aliquam facilisis erat sem, non fringilla neque sollicitudin ut. Cras quis tempor felis. Maecenas quis nisi pretium, malesuada risus quis, pulvinar nunc.</p>

                <p>Pellentesque ut neque vitae nibh malesuada commodo quis id nulla. Integer feugiat elementum lorem, quis mollis neque molestie ut. Cras in maximus metus. Cras vestibulum elit vel consequat rhoncus. Nullam vitae congue dui, vitae gravida magna. Nunc felis odio, fermentum vitae mi ac, sodales tempus orci. In auctor urna ac urna eleifend lobortis. Pellentesque sit amet ultrices turpis, id volutpat ligula. Nam et malesuada arcu. In hac habitasse platea dictumst. Sed mauris neque, porta sed tristique quis, dignissim at neque.</p>

                <p>Proin bibendum posuere quam quis efficitur. Morbi ligula mauris, bibendum vitae mi sit amet, ultrices placerat lectus. Ut dui lectus, ultricies sit amet est tempus, ultricies dignissim augue. In congue, augue ut sagittis sollicitudin, odio est volutpat sapien, ut vulputate arcu arcu vel sem. Praesent dapibus ipsum eu nisl porttitor posuere. Sed dolor odio, lacinia vitae dictum nec, imperdiet in dolor. Donec eros orci, fermentum id eleifend vitae, posuere condimentum arcu.</p>

                <div class="clearfix"></div>
            </div>
        </div>
    </div>
</main>