<main class="yellowWave">
    <div class="container">

        <div id="darkBackground" class="darkBackgroundHidden"></div>

        <h1>Billetterie</h1>
        <div class="centerSortingButton">
            <button id="sort" class="sortingButton">Trier</button>
        </div>
        
        
        <div id="buttons" class="filterContainer hiddenFilters">
            <button id="closeButtons" class="closeFilters"><i class="fas fa-xmark"></i></button>
            <div class="sortingButtons">
                Trier :
                <button id="sortByPrice">Par prix</button>
                <button id="sortByDate">Par date</button>
                <button id="sortByArtist">Par artiste</button>
                <button id="sortByCat">Par genre</button>
            </div>

            <form action="index.php?action=test" method="post" id="sortingForm" class="sortingForm">
            
                <div id="price" class="hidden">
                    <label class="hidden">Par prix</label>
                    <ul>
                        <li><input type="radio" name="sort" class="radioPrice" id="priceUp" value="ASC">croissant</li>
                        <li><input type="radio" name="sort" class="radioPrice" id="priceDown" value="DESC">décroissant</li>
                    </ul>
                </div>
                <div id="date" class="hidden">
                    <label class="hidden">Par date</label>
                    <ul>
                        <li><input type="radio" name="sort" class="radioDate" id="dateUp" value="recent">récente</li>
                        <li><input type="radio" name="sort" class="radioDate" id="dateDown" value="far">lointaine</li>
                    </ul>
                </div>
                <div id="artist" class="hidden">
                    <label class="hidden">Artiste</label>
                    <ul>
                        <?php foreach($artists as $artist) : ?>
                            <li><input type="radio" name="sort" class="radioArtist" value="<?= $artist['artist'] ?>"><?= $artist['artist'] ?></li>
                        <?php endforeach; ?>
                    </ul>
                </div>
                <div id="cat" class="hidden">
                    <label class="hidden">Genre</label>
                    <ul>
                        <?php foreach($cats as $cat) : ?>
                            <li><input type="radio" name="sort" class="radioCategory" value="<?= $cat['cat_name'] ?>"><?= $cat['cat_name'] ?></li>
                        <?php endforeach; ?>
                    </ul>
                </div>

            </form>
            
        </div>
        
        


        <div id="list" class="list">
            <?php foreach($events as $event) : ?>
                <div class="parent reveal">
                    <a href="index.php?action=event&id=<?= $event['id_event'] ?>">
                        <img src="www/images/posters/<?= $event["poster"] ?>" class="poster" alt="<?= $event["artist"] ?>">
                        <div class="posterArtist infoPoster"><?= $event["artist"] ?></div>
                        <div class="posterDay infoPoster"><?= $event["jour"] ?></div>
                        <div class="posterMonth infoPoster"><?= $event["mois"] ?></div>
                        <div class="posterYear infoPoster"><?= $event["annee"] ?></div>
                        <div class="posterName infoPoster"><?= $event["name"] ?></div>
                        <div class="posterCat infoPoster"><?= $event["category"] ?></div>
                    </a>
                </div>
            <?php endforeach; ?>
        </div>
    </div>
    <script type="text/javascript" src="www/js/filter.js"></script>
</main>